### ISSUE TITLE
Embedded SDK

### ISSUE THREAD

**Issue by ilrein** [froatsnook/meteor-shopify#1]
Hello,

Amazing library @froatsnook -- and awesome docs to boot.

Is it possible to use this library to create an embedded SDK app?

**Comment by froatsnook** [comment]
Wow, thank you!!

I have never created an embedded SDK app.  At a glance, it looks like it should be possible to make a small modification to `PublicAppOAuthAuthenticator` which redirects to a script as described [here](https://docs.shopify.com/embedded-app-sdk/getting-started).  I'm not sure what other changes would be helpful/necessary for embedded SDK app development.

So at the moment, no it's not supported.  Is this a feature that you would use?  If so, I will take a look!

**Comment by ilrein** [comment]
Undoubtedly, it would be the feature that could solidify this library the best Shopify/Meteor integration. Any Shopify developer worth their salt will be using the embed SDK to give their apps a native, integrated feel. It's a MUST have.

**Comment by froatsnook** [comment]
@ilrein 1.3.0 is published.  Let me know how it goes (if you try it) :)
