### ISSUE TITLE
api_key is not being picked up from keyset

### ISSUE THREAD

**Issue by 4Z4T4R** [froatsnook/meteor-shopify#10]
@froatsnook - I have a situation encountered and fixed.

```
# Server-Side CoffeeScript - Not using Meteor.startup 
# since it runs /after/ server side code ShopifyAPI executes 
# and I get type undefined errors.
# Defined in my:shopify package
# shopify-methods.coffee

Shopify.addKeyset "default", {
  api_key: Meteor.settings.private.SHOPIFY_API_KEY
  password: Meteor.settings.private.SHOPIFY_API_PASSWORD
}
ShopifyAPI = new Shopify.API {
  shop: 'my-shopify-app'
  keyset: 'default'
}
```

This yields the following error:

```
Error: api_key is required for Private Apps (assuming Private App because you provided a password
W20151216-16:43:42.106(-8)? (STDERR)    at new ShopifyAPI (packages/froatsnook_shopify/lib/api.js:85:1)
W20151216-16:43:42.106(-8)? (STDERR)     at Package (packages/my_shopify/shopify-methods.coffee:9:18)
```

Works fine when I omit the keyset and pass the values into `new Shopify:API`

**Comment by 4Z4T4R** [comment]
![image](https://cloud.githubusercontent.com/assets/2956998/11858484/f147f5e8-a416-11e5-82cb-5eea74bafd6d.png)

The error crops up on line 84. Earlier in the code you make the assignment to `this.config.password` from `keyset.password` as well as `this.config.api_key` from `keyset.api_key` but you short circuit the code by checking for `options.api_key` rather than `this.config.api_key`. The latter would work beautifully in all cases because of the assignment here:

![image](https://cloud.githubusercontent.com/assets/2956998/11858646/1c0901d6-a418-11e5-9995-109d904add39.png)

**Comment by froatsnook** [comment]
Hey @toszter, I'm glad you found this.  Bad problem, good fix.  I'm happy!  Thank you very much.
