### ISSUE TITLE
Callback for getThemes()

### ISSUE THREAD

**Issue by afang** [froatsnook/meteor-shopify#18]
What am I supposed to put in the callback for `api.getThemes()`? The console is giving me this error:

```Exception in delivering result of invoking 'froatsnook:shopify/HandleAuthRedirect': Error: Missing required param 'callback'
    at ShopifyAPI.API.(anonymous function) [as getThemes]```

In my React method:
```
 authenticate(e) {
        e.preventDefault();
        let storeName = ReactDOM.findDOMNode(this.refs.storeName).value.trim();
        console.log(`Authenticating ${storeName}...`);
        let authenticator = new Shopify.PublicAppOAuthAuthenticator({
            shop: storeName,
            api_key: '2ee8520dfad4a03788455a613f39e5fb',
            keyset: 'default',
            scopes: 'all', // request all permissions
            onAuth: function(accessToken) {
                Session.set('accessToken', accessToken);
                FlowRouter.go('/');
                $('.ui.modal.theme-import')
                    .modal('setting', {
                        closable: false,
                        transition: 'fade up'
                    })
                    .modal('show');

                let api = new Shopify.API({
                    shop: storeName,
                    backoff: 38,
                    insecure: true,
                    additionalHeaders: {
                        "X-DEV-MOOD": "Pensive"
                    }
                });
                console.log(api);
                console.log(api.getThemes());
            }
        });
        authenticator.openAuthTab();
    },
```

**Comment by afang** [comment]
Also, what's the best way to store the access key without using Accounts?

**Comment by dbnoble** [comment]
API functions on the front end are proxied through server method so they are expecting to deliver the result to your callback.

You need to do something like
````
api.getThemes(function(err, result) {
  if(!err) {
    console.log(result);
  }
});
````

**Comment by afang** [comment]
```
api.getThemes((err, res) => {
                    console.log(res);
                });
```
On the server side it's logging an auth error:

```
I20160210-02:30:16.433(-5)? Exception in setTimeout callback: TypeError: Cannot call method 'authenticate' of null
I20160210-02:30:16.433(-5)?     at eval (eval at <anonymous> (packages/froatsnook_shopify/lib/api.js:222:1), <anonymous>:44:25)
I20160210-02:30:16.433(-5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160210-02:30:16.434(-5)?     at packages/meteor/timers.js:6:1
I20160210-02:30:16.434(-5)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```
The list of themes aren't being logged in the client

**Comment by froatsnook** [comment]
That error means that self._authenticator is null [here](https://github.com/froatsnook/meteor-shopify/blob/master/lib/api.js#L282).  How are you creating `api`?

```javascript
if (Meteor.isServer) {
    Meteor.methods({
        "froatsnook:shopify/call": function(name, options, config) {
            // Retrieve cached server-side API object.
            var cachedAPI = Shopify._getCachedAPI(config);

            // Call the synchronous version of the method.
            return cachedAPI[name](options);
        }
    });
}
```

So when you call `api.getThemes` on the client, there's a cached API on the server that gets used.  The easiest way to do this is with keysets.  If you call `Shopify.addKeyset` somewhere with your `access_token`, then on the client you can do this (from the BasicExample):

```javascript
    var api = new Shopify.API({
        shop: shop,
        keyset: keyset,
    });

    api.countOrders(function(err, count) {
       // ...
    });
```

Is this a public app or a private app?

**Comment by froatsnook** [comment]
> Also, what's the best way to store the access key without using Accounts?

Unfortunately there's not a clear answer here.  If you call `Shopify.addKeyset`, you can store the `access_token` until the server restarts.  Maybe that's good enough for you.  I don't recommend using `shop` as the keyset name since (depending on how you implement things) it might be insecure.

If you give me some more info on how your app works I might be able to help!

**Comment by dbnoble** [comment]
> On the server side it's logging an auth error:

You are instantiating `Shopify.API` without a keyset. The keyset is what holds the access token for the `Shopify.API` methods.

I feel I should point out that you're getting the access token and then never doing anything with it other than assigning it to a Session variable, and maybe as you mentioned a property on your React object, although I don't see that in what you posted.

If you don't mind reauthenticating the user on every visit, I would probably do something like this in your onAuth callback

````
...
onAuth: function(accessToken) {

// Keysets are stored in memory on the SERVER
// so don't use the shop as the keyset name
var visitUUID = uuid.new();

// Save the UUID to Session instead of accessToken
Session.set('visitUUID', visitUUID);

Shopify.addKeyset(visitUUID, {
        access_token: accessToken
    });

// Now you can instantiate Shopify.API from anywhere using 
// the UUID to locate the keyset until the Session is cleared
 var api = new Shopify.API({
        shop: shop,
        keyset: Session.get('visitUUID'),
    });

// Do api stuff
api.getThemes(function(err, result) {
  if(!err) {
    console.log(result);
  }
});
...
````
You can use [rwatts:uuid](https://atmospherejs.com/rwatts/uuid) for the UUID generation.

This is basically an all-client-side implementation of the way I do it on the server. Only difference is that I persist the keysets and uuids. 

Since your keysets will not be reused on the next visit, I suggest scheduling a task to automatically remove each keyset after a certain amount of time.

**Comment by afang** [comment]
I have a `Exception in delivering result of invoking 'froatsnook:shopify/HandleAuthRedirect': TypeError: Shopify.addKeyset is not a function` error when adding the Keyset
```
authenticate(e) {
        e.preventDefault();
        let storeName = ReactDOM.findDOMNode(this.refs.storeName).value.trim();
        console.log(`Authenticating ${storeName}...`);
        let authenticator = new Shopify.PublicAppOAuthAuthenticator({
            shop: storeName,
            api_key: '2ee8520dfad4a03788455a613f39e5fb',
            keyset: 'default',
            scopes: 'all', // request all permissions
            onAuth: function(accessToken) {
                let visitUUID = uuid.new();
                Session.set('visitUUID', visitUUID);
                Shopify.addKeyset(visitUUID, {
                    access_token: accessToken
                });
                FlowRouter.go('/');
                $('.ui.modal.theme-import')
                    .modal('setting', {
                        closable: false,
                        transition: 'fade up'
                    })
                    .modal('show');

                let api = new Shopify.API({
                    shop: storeName,
                    keyset: Session.get('visitUUID')
                });

                api.getThemes((err, res) => {
                    console.log(res);
                });
            }
```

**Comment by froatsnook** [comment]
`Shopify.addKeyset` is server-only.

The proper way to do things is to:

1. Call `Shopify.harden()` in `Meteor.startup` on the server.  This way you don't need to expose the `accessToken` to the client.
2. Provide a `Shopify.onAuth` callback which creates the keyset.
3. Somehow communicate the keyset name to the client.  You could store it in the profile, use the shop name (insecure), or do something like this:

```javascript
var keysetNames = { };
Meteor.methods({
    prepareAuth: function(shop) {
        var keysetName = Random.id(17);
        keysetNames[shop] = keysetName;
        return keysetName;
    },
});
```

Then the client would have the keyset name before it's created and can use it in `onAuth` (`onAuth` should be called on the client after it is called on the server).  And the server would have the keyset name for creation in `keysetNames`.

**Comment by froatsnook** [comment]
I'm going to generate a uuid called `authId` and pass it to both server-side and client-side `onAuth`s.  This should make keyset name generation easier.

**Comment by dbnoble** [comment]
> Shopify.addKeyset is server-only

You are correct there, sorry I should have mentioned that. You should wrap that part in a method call if you want to do to it from the client side.
