### ISSUE TITLE
Defining New API Methods

### ISSUE THREAD

**Issue by ilrein** [froatsnook/meteor-shopify#3]
Hey @froatsnook,

I'm still coding away at Shopify apps and making use of this library heavily.

I noticed that there aren't any methods for the script tag: https://docs.shopify.com/api/uiintegrations/scripttag#index

So, I tried to use the define approach:

`var shop = Meteor.user().profile.shopName;
  var access_token = Meteor.user().profile.shopifyAccessToken;
  var api = new Shopify.API({
    shop: shop,
    access_token: access_token,
    insecure: true  
  });`

`Shopify.API.define({
    "name": "getAllScriptTags",
    "method": "GET",
    "path": "/admin/script_tags.json",
    "returns": "scripttags",
    "description": "Get all script tags"
  });`

  `var scripts = api.getAllScriptTags();
  console.log(scripts);
  return scripts;`

This is inside a `Meteor.method`. My result is always `undefined`.  Any suggestions?

**Comment by froatsnook** [comment]
Hey @ilrein 

It looks like the only problem with this is that it should return `script_tags` (with an underscore). 

Could there ever be more than 50 results? If so, use Shopify.API.defineConcat. That way it will return more than 50 if necessary. 

I'm away from my computer for a couple weeks, but I'll give this a try and add it to the library when I get a chance :).

**Comment by ilrein** [comment]
Yes! I got it!

Thanks so much for the fast responses, even when you're on vacation or whatnot. 

I see that the "returns" actually references the key from Shopify's response object. It all makes sense now.

EDIT: I'm trying to "POST" a script tag (everything is on the server side) --

  `Shopify.API.define({
      "name": "postScriptTag",
      "method": "POST",
      "path": "/admin/script_tags.json",
      "returns": "script_tag",
      "description": "Post new script tag"
    });`

```
`var params = {
  "script_tag": {
    "event": "onload",
    "src": "https:\/\/www.ajaxinfinityscroll.com\/javascripts\/infinityscroll.js"
  }
};`
```

`var newScript = api.postScriptTag(params);`

I feel as though the above code SHOULD work, but it doesn't:

`Error: failed [400] {"errors":{"script_tag":"expected String to be a Hash"}}`

UPDATE: I'm convinced the above error is an issue with the package code. Perhaps you have not had a chance to try a POST request? The README doesn't have any POST examples. I suspect there might be a bug somewhere. I was able to POST a script tag (thanks to the access token) with just HTTP.

`var newScript = HTTP.post("https://" + Meteor.user().profile.shopName + ".myshopify.com/admin/script_tags.json" , options);`

**Comment by froatsnook** [comment]
Hi @ilrein.  Sorry I missed this message.  I think I'm using `POST` in production.  Let me get back to you on that!

**Comment by froatsnook** [comment]
@ilrein You're right.  I'm using `POST` but only with an empty request body.  I'll get a new version up ASAP.  Thanks for reporting!

**Comment by froatsnook** [comment]
Hey @ilrein 1.4.0 adds support for specifying the request body.  This should let you create metafields properly.

Documented [here](https://github.com/froatsnook/meteor-shopify/commit/60a1360abc998a912ec65eb20209a7dfc50729bf).

Thanks for reporting and please let me know if you have other issues!
