### ISSUE TITLE
Basic tutorial?

### ISSUE THREAD

**Issue by galenking** [froatsnook/meteor-shopify#4]
Hey @froatsnook, thanks for this! It's fantastic.

I'm a total Meteor novice and was hoping I could quickly get something working but I am totally struggling to get this to work—even in a simple form.

Would it be too much to ask for a few code samples for the server, client and template to get this working?

When I attempt to use this, I am stuck on what should be in "server" code and what should be in "client" code. It just doesn't work.

Anyway, thanks for creating this.

**Comment by froatsnook** [comment]
Hey @galenking. Thank you! And welcome to Meteor :). 

Sure, I can make a basic tutorial. I will try to push something tonight.

**Comment by galenking** [comment]
Thanks @froatsnook. I did get it working but was having some sort of issue with the authentication on the callback. I think my problem is I'm just not entirely sure how to set up up—what's on the server, what's on the client etc.

**Comment by froatsnook** [comment]
Hi @galenking Yes, that's understandable. Are you using a private or a public app? And what is the goal of your program? I think I can guide you better with a bit more info.

**Comment by galenking** [comment]
Thanks @froatsnook. I'm basically wanting to be able to very simply output all open orders and all products from open orders.

At least initially.

Once I've got the gist of how this works, anything else should be straightforward. Ideally, I am wanting a public app.

**Comment by froatsnook** [comment]
Hey @galenking.  I started on a basic tutorial.  It will be up in a few days.  I'll write again here when it's done :).

**Comment by galenking** [comment]
Hi @froatsnook, sorry to chase you! I don't mean to. Just wondering if you got the tutorial done? If not, no worries. I really appreciate what you have created regardless! :)

**Comment by froatsnook** [comment]
Hey @galenking.  Sorry for the delay.  I started working on it and haven't had time to finish.  I hope to get around to finishing it soon!

**Comment by galenking** [comment]
Thanks @froatsnook.

**Comment by bytesandwich** [comment]
Hey @froatsnook do you have an example with everything wired together the way you intend?

**Comment by froatsnook** [comment]
Hey @jackphel, have you seen the EmbeddedAppSDKTest?  All the pieces are there, and maybe it will hold you over until I make a simpler example.  It's more like an example than a test!

**Comment by froatsnook** [comment]
@galenking @jackphel.  Check out BasicExample.  It has everything wired how I intend.

If you need client-side API access then you'll also need to do this to make it secure:
1. On auth, store the accessToken in Meteor.users (not in the profile => not sent to user)
2. Also store a uuid in the user's profile called `keyset`
3. Also store the shop in the user's profile.
4. Also call `Shopify.onAuth(user.accessToken, user.profile.keyset)`
5. When the server starts, iterate over users calling `Shopify.addKeyset(user.profile.keyset, user.accessToken)`

Once you've done this, then `new Shopify.API({ shop: user.profile.shop, keyset: user.profile.keyset })` will work client-side and server-side.
